server:
  port: 8000
  servlet:
    context-path: / # http://localhost:8000/
  encoding:
    charset: UTF-8
    enabled: true
    force: true

spring:
  application:
    name: blog

  config:
    import: 
      - "application-db.yml"

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jackson:
    serialization:
      fail-on-empty-beans: false		
# mybatis 설정
mybatis:
  mapper-locations:
    - classpath:mybatis-mapper/mysql/*.xml  # mysql 폴더 매핑
    - classpath:mybatis-mapper/oracle/*.xml # oracle 폴더 매핑
  config-location: classpath:mybatis-config.xml