spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mybatis_blogdb?serverTimezone=Asia/Seoul
        username: psb3505
        password: zcbadg19487.
        driver-class-name: com.mysql.cj.jdbc.Driver